general {
    gaps_in = 2
    gaps_out = 4
    border_size = 2 # Thin lines look more futuristic/techy
    col.active_border = rgba(a020f0ee) 
    col.inactive_border = rgba(1a1a1aee)

    layout = dwindle
}

decoration {
    rounding = 0 # Sharp corners feel more like a "Cyberdeck" tool

    active_opacity = 0.85
    inactive_opacity = 0.8 # Darkens background windows for focus

    blur {
        enabled = true
        size = 3
        passes = 1
        brightness = 0.5 # Keeps it dark
    }

    shadow {
        enabled = false # Shadows are too "soft" for a minimalist deck
    }
}

animations {
    enabled = yes please
}
