exec-once = awww-daemon
exec-once = awww img ~/Documents/wallpapers/lucy.jpg

exec-once = waybar

exec-once = wl-paste --type text --watch cliphist store # Stores only text data
exec-once = wl-paste --type image --watch cliphist store # Stores only image data

exec-once = touchegg
